language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

# set up allowed failures in the matrix
matrix:
  allow_failures:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 7.0
    - php: 7.1
    - php: hhvm
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
   - sudo apt-get update -qq

install:
    - curl -sS https://getcomposer.org/installer | php
    - composer self-update
    - composer install --prefer-source --no-interaction --dev
    # - if [[ $HHVM == true ]]; then composer require "phpunit/phpunit:5.7"; fi

before_script:
    - php --version
    - php composer.phar composer --version
    - php composer.phar install
    - travis_retry composer install --dev --prefer-dist

script:
    - phpunit .

after_failure:
  - cat MSBuild_*.failure.txt
